docker/web/source/wizard/views.py
from flask import redirect, render_template, url_for, request, Blueprint
from .models import System, Network, SystemType, NetworkType, CBox, ScanCategory
from .forms import NetworkForm, SystemForm, BOX4sForm
from .middleware import WizardMiddleware
from source.extensions import db
from sqlalchemy.exc import SQLAlchemyError
from flask.helpers import flash

import tempfile
import shutil
import os
import re

bpWizard = Blueprint('wizard', __name__, template_folder='templates')


@bpWizard.before_request
def check_if_wizard():
    if not WizardMiddleware.isShowWizard():
        return redirect(url_for('index'))


@bpWizard.route('/', methods=['GET', 'POST'])
def index():
    return render_template('wizard/index.html')


@bpWizard.route('/networks', methods=['GET', 'POST'])
def networks():
    formNetwork = NetworkForm(request.form)
    formNetwork.types.choices = [(t.id, t.name) for t in NetworkType.query.order_by('id')]
    formNetwork.scancategory_id.choices = [(c.id, c.name) for c in ScanCategory.query.order_by('id')]
    if request.method == 'POST':
        if formNetwork.validate():
            newNetwork = Network()
            formNetwork.populate_obj(newNetwork)  # Copies matching attributes from form onto newNetwork
            if newNetwork.types:
                newNetwork.types = [NetworkType.query.get(tid) for tid in newNetwork.types]  # Get actual type objects from their IDs
            db.session.add(newNetwork)
            db.session.commit()
            return redirect(url_for('wizard.networks'))
    networks = Network.query.order_by(Network.id.asc()).all()
    scan_categories = ScanCategory.query.order_by(ScanCategory.id.asc()).all()
    return render_template('wizard/networks.html', formNetwork=formNetwork, networks=networks, scan_categories=scan_categories)


@bpWizard.route('/box4s', methods=['GET', 'POST'])
def box4s():
    formBOX4s = BOX4sForm(request.form)
    formBOX4s.network_id.choices = [(n.id, f"{n.name} ({n.ip_address}/{n.cidr})") for n in Network.query.order_by('id')]
    formBOX4s.dns_id.choices = [(s.id, f"{s.name} ({s.ip_address})") for s in System.query.order_by('id').filter(System.types.any(name='DNS-Server'))]
    formBOX4s.dns_id.choices += [(-1, "Autre..")]
    formBOX4s.gateway_id.choices = [(s.id, f"{s.name} ({s.ip_address})") for s in System.query.order_by('id').filter(System.types.any(name='Gateway'))]
    formBOX4s.gateway_id.choices += [(-1, "Autre..")]
    systemTypes = SystemType.query.filter(SystemType.name != 'CBox').order_by(SystemType.id.asc()).all()
    BOX4s = CBox.query.order_by(CBox.id.asc()).first()
    if request.method == 'POST':
        if formBOX4s.validate():
            if not BOX4s:
                # BOX4s does not exist => create anew.
                BOX4s = CBox()
            formBOX4s.populate_obj(BOX4s)  # Copies matching attributes from form onto box4s
            BOX4s.name = "CBox"
            BOX4s.ids_enabled = False
            BOX4s.scan_enabled = False
            BOX4s.types = [SystemType.query.filter(SystemType.name == 'CBox').first()]
            BOX4s.dns = System.query.get(BOX4s.dns_id)
            BOX4s.gateway = System.query.get(BOX4s.gateway_id)
            try:
                db.session.add(BOX4s)
                db.session.commit()
            except SQLAlchemyError:
                flash('La configuration n\'a pas pu être enregistrée.', category="error")
            else:
                flash('La configuration a été reçue.', category="success")
            return redirect(url_for('wizard.box4s'))
    return render_template('wizard/box4s.html', formBOX4s=formBOX4s, box4s=BOX4s, systemTypes=systemTypes)


@bpWizard.route('/systems', methods=['GET', 'POST'])
def systems():
    formSystem = SystemForm(request.form)
    formSystem.network_id.choices = [(n.id, f"{n.name} ({n.ip_address}/{n.cidr})") for n in Network.query.order_by('id')]
    formSystem.types.choices = [(t.id, t.name) for t in SystemType.query.order_by('id').filter(SystemType.name != 'CBox')]
    if request.method == 'POST':
        if formSystem.validate():
            newSystem = System()
            formSystem.populate_obj(newSystem)  # Copies matching attributes from form onto newSystem
            if newSystem.types:
                newSystem.types = [SystemType.query.get(tid) for tid in newSystem.types]  # Get actual type objects from their IDs
            db.session.add(newSystem)
            db.session.commit()
            return redirect(url_for('wizard.systems'))
    systems = System.query.order_by(System.id.asc()).all()
    return render_template('wizard/systems.html', formSystem=formSystem, systems=systems)


@bpWizard.route('/mail', methods=['GET', 'POST'])
def smtp():
    return render_template('wizard/mail.html')


@bpWizard.route('/verify', methods=['GET', 'POST'])
def verify():
    if request.method == 'POST':
        apply()
        return render_template('wizard/verify_progress.html')
    networks = Network.query.order_by(Network.id.asc()).all()
    systems = System.query.order_by(System.id.asc()).all()
    BOX4s = CBox.query.order_by(CBox.id.asc()).first()
    scan_categories = ScanCategory.query.order_by(ScanCategory.id.asc()).all()
    return render_template('wizard/verify.html', networks=networks, systems=systems, box4s=BOX4s, scan_categories=scan_categories)


def apply():
    """Apply the configuration."""
    # Step 0: Query Information.
    networks = Network.query.order_by(Network.id.asc()).all()
    systems = System.query.order_by(System.id.asc()).all()
    BOX4s = CBox.query.order_by(CBox.id.asc()).first()

    # Step 1: Set DNS in resolv.personal
    with open('/var/lib/cbox/resolv.personal', 'w') as fd_resolv:
        fd_resolv.write(f'nameserver {BOX4s.dns.ip_address}\n')
    fd_resolv.close()

    # Step 2: Set INT_IP in /etc/environment
    tmp, tmp_path = tempfile.mkstemp(text=True)
    with open('/etc/environment', 'r') as fd_env:
        with open(tmp, 'w') as fd_tmp:
            for line in fd_env:
                if "CLIENT=" in line:
                    line = "CLIENT={client}\n".format(client='NEWCLIENT')
                elif "INT_IP=" in line:
                    line = f"INT_IP={BOX4s.ip_address}\n"
                fd_tmp.write(line)
            fd_tmp.seek(0)
        shutil.copyfile(tmp_path, '/etc/environment')
    os.remove(tmp_path)
    fd_env.close()
    # Step 3:

    # Step 4: Apply networks to logstash configuration.

    # Prepare list for IPs to drop and not track (ids_enabled = False)
    drop_systems_iplist = ["f{ip_address}" for ip_address, in db.session.query(System.ip_address).filter(System.ids_enabled is False).all()]
    drop_systems_iplist += ['localhost', '127.0.0.1', '127.0.0.53']
    drop_systems_iplist += [f"{BOX4s.ip_address}"]

    # Render the templates and fill with data
    templateDrop = render_template('logstash/drop.jinja2', iplist=drop_systems_iplist)
    templateNetworks = render_template('logstash/network.jinja2', networks=networks)
    templateSystems = render_template('logstash/system.jinja2', systems=systems)

    # Render the final template from smaller templates.
    templateBOX4sSpecial = render_template('logstash/CBox-special.conf.jinja2', templateDrop=templateDrop, templateNetworks=templateNetworks, templateSystems=templateSystems)

    # Write the replaced text to the original file, replacing it.
    with open('/etc/cbox/logstash/CBox-special.conf', 'w', encoding='utf-8') as fd_4sspecial:
        fd_4sspecial.write(templateBOX4sSpecial)

    # Step 5: Apply INT_IP to Logstash Default.
    with open('/etc/default/logstash', 'r', encoding='utf-8') as fd_deflogstash:
        content = fd_deflogstash.read()
        content = re.sub(r'(INT_IP=)([0-9\.]+)()', r'\g<1>{}'.format(BOX4s.ip_address), content)
        content = re.sub(r'(CLIENT=)(\w+)()', r'\g<1>{}'.format("NEWCLIENT"), content)
    with open('/etc/default/logstash', 'w', encoding='utf-8') as fd_deflogstash:
        fd_deflogstash.write(content)

    # Step 6: Set network configuration for CBox.
    templateNetplan = render_template('logstash/netplan.yaml.jinja2', BOX4s=BOX4s)
    with open('/etc/_netplan/10-cbox.yaml', 'w', encoding='utf-8') as fd_netplan:
        fd_netplan.write(templateNetplan)

    # Step 7: Set the completed state.
    WizardMiddleware.setCompleted()

docker/web/source/wizard/templates/wizard/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% block head %}
        <link rel="stylesheet" href="/static/external/semantic.min.css">
        <link rel="stylesheet" type="text/css" href="/static/box4s.css">
        <title>CyberBox</title>
        {% endblock %}
    </head>
    <body>
        <div class="container ui middle aligned center aligned one column grid">
            <div class="one column">
                <img src="/static/CBox_Logo.png" class="ui centered large image" />
            </div>
            <div class="one column">
                <div class="ui six top attached ordered steps">
                    <a id='step-index' class="active step" href="{{ url_for('wizard.index') }}">
                        <div class="content">
                            <div class="title">Démarrer</div>
                        </div>
                    </a>
                    <a id='step-networks' href="{{ url_for('wizard.networks') }}" class="step">
                        <div class="content">
                            <div class="title">Réseaux</div>
                        </div>
                    </a>
                    <a id='step-systems' href="{{ url_for('wizard.systems') }}" class="step">
                        <div class="content">
                            <div class="title">Système</div>
                        </div>
                    </a>
                    <a id='step-box4s' href="{{ url_for('wizard.box4s') }}" class="step">
                        <div class="content">
                            <div class="title">CBox</div>
                        </div>
                    </a>
                    <a id='step-smtp' href="{{ url_for('wizard.smtp') }}" class="step">
                        <div class="content">
                            <div class="title">SMTP</div>
                        </div>
                    </a>
                    <a id='step-verify' href="{{ url_for('wizard.verify') }}" class="step">
                        <div class="content">
                            <div class="title">Vérification</div>
                        </div>
                    </a>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="ui one column">
                {% for category, message in messages %}
                    <div class="ui {{ category }} message">
                        <p>{{ message }}</p>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="ui vertical foursfooter footer segment">
            <div class="ui center aligned container">
                <img src="/static/CBox_Logo.png" class="ui centered small image">
            </div>
        </div>
        {% block modal %}{% endblock %}
        <script src="/static/external/jquery.min.js"></script>
        <script src="/static/external/semantic.min.js"></script>
        <script src='/static/wizard.js'></script>
        <script>
        $('.ui.dropdown').dropdown();
        $('.ui.checkbox').checkbox();
        </script>
        {% block scripts %}{% endblock %}
    </body>
</html>

docker/web/source/wizard/templates/wizard/box4s.html
{% extends "wizard/base.html" %}
{% block content %}
{% from "user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
    <div class="one column">
    <div class="ui segment">
        <div class="ui success message">
            <div class="header">
                Configuration de CBox
            </div>
            <p>
                Effectuez les réglages importants pour la connectivité de CBox ici.<br>
                Les modifications prendront effet à l'étape 6 une fois la configuration terminée.
            </p>
        </div>
        <form class="ui form" action="" method="POST" role="form">
            {{ formBOX4s.hidden_tag() }}
            <h3 class="ui dividing header">Configuration réseau CBox</h3>
            <div class="centered inline field">
                <div class="ui toggle checkbox">
                    <input id="{{ formBOX4s.dhcp_enabled.id }}" name="{{ formBOX4s.dhcp_enabled.name }}" type="checkbox" class="hidden">
                    <label>DHCP utiliser</label>
                </div>
            </div>
            {% if formBOX4s.dhcp_enabled.errors %}
                {% for e in formBOX4s.dhcp_enabled.errors %}
                <p class="ui orange message">{{ e }}</p>
                {% endfor %}
            {% endif %}
            <h5 class="ui dividing header"> - ou -</h5>
            <div class="two fields">
                <div class="field">
                    <label>Affiliation au réseau CBox</label>
                    <select id="{{formBOX4s.network_id.id}}" name="{{formBOX4s.network_id.name}}" required="" class="ui dropdown">
                    <option value="">Réseau</option>
                    {% for value in formBOX4s.network_id.choices %}
                        <option value="{{value[0]}}">{{value[1]}}</option>
                    {% endfor %}
                    </select>
                </div>
                {% if formBOX4s.network_id.errors %}
                    {% for e in formBOX4s.network_id.errors %}
                    <p class="ui orange message">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                <div class="field">
                    <label>IP-Adresse CBox</label>
                    <input type="text" id="{{ formBOX4s.ip_address.id }}" name="{{ formBOX4s.ip_address.name }}" placeholder="IP-Adresse (par ex. 192.168.1.0)">
                </div>
                {% if formBOX4s.ip_address.errors %}
                    {% for e in formBOX4s.ip_address.errors %}
                    <p class="ui orange message">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="two fields">
                <div class="field">
                    <label>DNS-Server CBox</label>
                    <select id="{{formBOX4s.dns_id.id}}" name="{{formBOX4s.dns_id.name}}" required="" class="ui dropdown">
                    <option value="">DNS-Server</option>
                    {% for value in formBOX4s.dns_id.choices %}
                        <option value="{{value[0]}}">{{value[1]}}</option>
                    {% endfor %}
                    </select>
                </div>
                {% if formBOX4s.dns_id.errors %}
                    {% for e in formBOX4s.dns_id.errors %}
                    <p class="ui orange message">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                <div class="field">
                    <label>Gateway CBox</label>
                    <select id="{{formBOX4s.gateway_id.id}}" name="{{formBOX4s.gateway_id.name}}" required="" class="ui dropdown">
                    <option value="">Gateway</option>
                    {% for value in formBOX4s.gateway_id.choices %}
                        <option value="{{value[0]}}">{{value[1]}}</option>
                    {% endfor %}
                    </select>
                    {% if formBOX4s.gateway_id.errors %}
                        {% for e in formBOX4s.gateway_id.errors %}
                        <p class="ui orange message">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <button type="submit" class="ui large foursgrey-bg button">Sauvegarder</button>
        </form>
    </div>
    </div>
    <div class="ui one column">
        <a href="{{ url_for('wizard.smtp') }}" class="ui large foursgrey-bg button">Continuer</a>
    </div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$('.step.active').removeClass('active');
$('#step-box4s').addClass('active');
</script>
<script>
    $('#{{formBOX4s.dns_id.id}}').parent('.ui.dropdown')
    .dropdown({
        onChange: function(value, text, $selectedItem) {
            if(value == -1)
            {
                // "Others" selected, display menu
                $('#modal-add-other').modal('show');
                $('#add-other-submit').data('systemtype', 'DNS-Server');
            }
        }
    });
    $('#{{formBOX4s.gateway_id.id}}').parent('.ui.dropdown')
    .dropdown({
        onChange: function(value, text, $selectedItem) {
            if(value == -1)
            {
                // "Others" selected, display menu
                $('#modal-add-other').modal('show');
                $('#add-other-submit').data('systemtype', 'Gateway');
                
            }
        }
    });
    // TODO: Handle Constants from API
    const typeIDDns = 2;
    const typeIDGateway = 3;
    $('#add-other-submit').on('click', (e) => {
        const modalSystemType = $(e.currentTarget).data('systemtype');
        e.preventDefault();
        var data = {
            'name': $('#add-other-name').val(),
            'ip_address': $('#add-other-ip_address').val(),
            'ids_enabled': $('#add-other-ids_enabled').prop("checked"),
            'scan_enabled': $('#add-other-scan_enabled').prop("checked"),
            'types': $('#add-other-types').val(),
            'network_id': $('#add-others-network_id').val(),
        };
        
        if(data.types.indexOf(typeIDDns) == -1 && modalSystemType == 'DNS-Server')
        {
            data.types.push(typeIDDns);
        }
        else if(data.types.indexOf(typeIDGateway) == -1 && modalSystemType == 'Gateway')
        {
            data.types.push(typeIDGateway);
        }
        fetch(`/api/systems/`,
            {
              method: 'POST',
              headers: {'Content-Type': 'application/json'},
              body: JSON.stringify(data),
            })
        .then(response => {
            if(!response.ok) {
                var errormsg = "";
                switch(response.status) {
                    case 400: errormsg = "La demande contenait des paramètres incompréhensibles pour le traitement."; break;
                    case 500: errormsg = "Le système n'a pas pu être enregistré dans la base de données."; break;
                    case 503: errormsg = "L'assistant de configuration n'est plus disponible."; break;
                };
                row = `<div class="ui red message">${errormsg}</div>`;
                $(`#edit-submit`).before(row);
            } else {
                response.json().then( d => {

                    // Submission successful => use system in dialog.
                    var option = document.createElement("option");
                    if (modalSystemType == "DNS-Server") {
                        var s = $('#{{formBOX4s.dns_id.id}}');
                    } else if(modalSystemType == "Gateway") {
                        var s = $('#{{formBOX4s.gateway_id.id}}');
                    }
                    if(d.name) {
                        option.text = `${d.name} (${d.ip_address})`;
                    } else {
                        option.text = `${d.ip_address}`;
                    }
                    option.value = d.id;
                    s.append(option);
                    setTimeout(
                        // oddly append needs some time to append, and we can not call .dropdown before
                        () => {
                            s.parent('.ui.dropdown').dropdown("set selected", d.id);
                            $('#modal-add-other').modal('hide');
                            $('#modal-add-other > > form')[0].reset();
                        }, 350
                    );
                });
            }            
        })

    });
</script>
{% if box4s %}
<script type="text/javascript">
$('#{{formBOX4s.dhcp_enabled.id}}').parent('.ui.checkbox').checkbox('setting', 'onChange', function () {
    if($('#{{formBOX4s.dhcp_enabled.id}}').parent('.ui.checkbox').checkbox('is checked')) {
        $('#{{formBOX4s.network_id.id}}').parent('.ui.dropdown').addClass("disabled");
        $('#{{formBOX4s.ip_address.id}}').prop('disabled', true);
        $('#{{formBOX4s.dns_id.id}}').parent('.ui.dropdown').addClass("disabled");
        $('#{{formBOX4s.gateway_id.id}}').parent('.ui.dropdown').addClass("set disabled");
    } else {
        $('#{{formBOX4s.network_id.id}}').parent('.ui.dropdown').removeClass("disabled");
        $('#{{formBOX4s.ip_address.id}}').prop('disabled', false);
        $('#{{formBOX4s.dns_id.id}}').parent('.ui.dropdown').removeClass("disabled");
        $('#{{formBOX4s.gateway_id.id}}').parent('.ui.dropdown').removeClass("disabled");
    }
});

$('#{{formBOX4s.network_id.id}}').parent('.ui.dropdown').dropdown("set selected", "{{box4s.network.id}}");
$('#{{formBOX4s.ip_address.id}}').val("{{box4s.ip_address}}");
$('#{{formBOX4s.dns_id.id}}').parent('.ui.dropdown').dropdown("set selected", "{{box4s.dns_id}}");
$('#{{formBOX4s.gateway_id.id}}').parent('.ui.dropdown').dropdown("set selected", "{{box4s.gateway_id}}");

{% if box4s.dhcp_enabled %}
$('#{{formBOX4s.network_id.id}}').parent('.ui.dropdown').addClass("disabled");
$('#{{formBOX4s.ip_address.id}}').prop('disabled', true);
$('#{{formBOX4s.dns_id.id}}').parent('.ui.dropdown').addClass("disabled");
$('#{{formBOX4s.gateway_id.id}}').parent('.ui.dropdown').addClass("disabled");
$('#{{formBOX4s.dhcp_enabled.id}}').parent('.ui.checkbox').checkbox("set checked");
{% endif %}
</script>
{% endif %}
<script type="text/javascript">
    
</script>
{% endblock %}
{% block modal %}
<div id="modal-add-other" class="ui tiny modal">
    <i class="close icon"></i>
    <div class="header">Autre ..</div>
    <div class="content">
        <form class="ui equal width small form" action="" method="POST" role="form">
            <div class="fields">
                <div class="sixteen wide field">
                    <label>Identifiant-Système</label>
                    <div class="ui left icon input">
                    <i class="map sig icon"></i>
                    <input type="text" id="add-other-name" required="" name="add-other-name" placeholder="Identifiant-Système">
                    </div>
                </div>
            </div>
            <div class="fields">
                <div class="field">
                    <label>Affiliation au réseau (optional)</label>
                    <select id="add-other-network_id" name="add-other-network_id" class="ui dropdown">
                    <option value="">Réseau</option>
                    {% for value in formBOX4s.network_id.choices %}
                        <option value="{{value[0]}}">{{value[1]}}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <div class="fields">
                <div class="field">
                    <label>IP-Adresse</label>
                    <input type="text" id="add-other-ip_address" name="add-other-ip_address" placeholder="IP-Adresse (par ex. 192.168.1.1)">
                </div>
            </div>
            <div class="fields">
                <div class="ten wide field">
                    <label>Type-Système</label>
                    <select id="add-other-types" name="add-other-types" multiple="" class="ui dropdown">
                    <option value="">Type-Système</option>
                    {% for t in systemTypes %}
                        <option value="{{t.id}}">{{t.name}}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <h4 class="ui dividing header">Options-CBox</h4>
            <div class="fields">
                <div class="fields">
                    <div class="inline field">
                        <div class="ui checkbox">
                          <input id="add-other-scan_enabled" name="add-other-scan_enabled" type="checkbox" class="hidden">
                          <label>Effectuer des scan de vulnérabilité pour ce système</label>
                        </div>
                    </div>
                    <div class="inline field">
                        <div class="ui checked checkbox">
                          <input id="add-other-ids_enabled" name="add-other-ids_enabled" checked="" type="checkbox" class="hidden">
                          <label>Traffic-Analyse effectuer pour ce système (conseillé)</label>
                        </div>
                    </div>
                </div>
            </div>
            <button id="add-other-submit" class="ui fluid large foursgrey-bg submit button" type="submit" name="button">Ajouter</button>
        </form>
    </div>
</div>
{% endblock %}

docker/web/source/wizard/templates/wizard/index.html
{% extends "wizard/base.html" %}
{% block content %}
{% from "user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
    <div class="one column">
        <div class="ui segment">
            <div class="ui success message">
                <div class="header">
                    Configuration initiale de CBox
                </div>
                <p>
                    Une configuration initiale est requise pour utiliser CBox. <br>
                    Il est mis en place à l'aide d'une série de formulaires que vous traitez les uns après les autres. <br>
                    Après avoir confirmé chaque étape, les données stockées seront enregistrées. <br>
                    Vous pouvez toujours revenir en arrière dans les étapes pour corriger un paramètre. <br>
                    Après avoir finalement vérifié les données à l'étape 6, les modifications prendront effet.
                </p>
            </div>
            <a href="{{ url_for('wizard.networks') }}" class="ui large foursgrey-bg button">Démarrer la configuration</a>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$('.step.active').removeClass('active');
$('#step-index').addClass('active');
</script>
{% endblock %}

docker/web/source/wizard/templates/wizard/verify_progress.html
{% extends "wizard/base.html" %}
{% block content %}
<div class="ui one column">
    <div class="ui active centered inline massive loader"></div>
</div>
<div class="ui one column">
    <div class="ui message">
        <div class="header">L'heure viendra bientôt...</div>
        <div class="content">Vous avez confirmé vos entrées. CBox va maintenant être configurée. S'il vous plaît soyez patient.</div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$('.step.active').removeClass('active');
$('#step-verify').addClass('active');
$('#progress').progress();
</script>
{% endblock %}